---
abstract: 'checkupdates for packages installed from AUR'
author:
  - '3ED <krzysztof1987@gmail.com>'
build_requires:
  Test::More: '0'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.422, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OS-CheckUpdates-AUR
provides:
  OS::CheckUpdates::AUR:
    file: lib/OS/CheckUpdates/AUR.pm
    version: '0.05'
  OS::CheckUpdates::AUR::Capture:
    file: lib/OS/CheckUpdates/AUR.pm
  OS::CheckUpdates::AUR::stats:
    file: lib/OS/CheckUpdates/AUR.pm
requires:
  Capture::Tiny: '0'
  JSON: '0'
  Try::Tiny: '0'
  WWW::AUR: '0.19'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
version: '0.05'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
